In [1]:
'''
1 Titanic datasetini gətirib ordakı bütün məlumatları göstərin.(Dataseti analiz edin)

2.Qadın sərnişinlərin ortalama yaşları neçədir?

3."PassengerId", "Name" və "Ticket" sütunlarını silin və yenidən dataseti çağırdıqda o sütunlar görünməsin

4.Gediş haqqı üçün 7000 və ondan az ödəmə edən müştərilərin sayın gətirin (məlumatlar gəlməsin sadəcə say gəlsin)

5.Həyatda qalan sərnişinlər toplam sərnişinlərin neçə faizidir?


6.ən yaşlı və ən gənc sərnişinlərin yaşı neçədir?

7.Sərnişinlərdən neçəsi ailə üzvləriylə bir yerdə səyahət edib?

8.Bütün Kabin nömrələrini göstərin (təkrarlanmasın)
'''

'\n1 Titanic datasetini gətirib ordakı bütün məlumatları göstərin.(Dataseti analiz edin)\n\n2.Qadın sərnişinlərin ortalama yaşları neçədir?\n\n3."PassengerId", "Name" və "Ticket" sütunlarını silin və yenidən dataseti çağırdıqda o sütunlar görünməsin\n\n4.Gediş haqqı üçün 7000 və ondan az ödəmə edən müştərilərin sayın gətirin (məlumatlar gəlməsin sadəcə say gəlsin)\n\n5.Həyatda qalan sərnişinlər toplam sərnişinlərin neçə faizidir?\n\n\n6.ən yaşlı və ən gənc sərnişinlərin yaşı neçədir?\n\n7.Sərnişinlərdən neçəsi ailə üzvləriylə bir yerdə səyahət edib?\n\n8.Bütün Kabin nömrələrini göstərin (təkrarlanmasın)\n'

In [32]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
df=pd.read_csv("titanic.csv")

In [27]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [29]:
#2.Qadın sərnişinlərin ortalama yaşları neçədir?
df[df["Sex"]=="female"].mean(numeric_only=True)[["Age"]]

Age    27.915709
dtype: float64

In [34]:
#3."PassengerId", "Name" və "Ticket" sütunlarını silin və yenidən dataseti çağırdıqda o sütunlar görünməsin

df.drop("PassengerId" , axis = 1, inplace=True) # ve ya df.drop("C1", axis = 1, inplace = True)
df.drop("Name" , axis = 1, inplace=True)
df.drop("Ticket" , axis = 1, inplace=True)

In [35]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [49]:
#4.Gediş haqqı üçün 7000 və ondan az ödəmə edən müştərilərin sayın gətirin (məlumatlar gəlməsin sadəcə say gəlsin)
df[df["Fare"]<=7000].count()[["Fare"]]

Fare    891
dtype: int64

In [63]:
#5.Həyatda qalan sərnişinlər toplam sərnişinlərin neçə faizidir?
percentage=df[df["Survived"]==1].count()[["Survived"]]/df.count()[["Survived"]] *100
print(round(percentage,2))

Survived    38.38
dtype: float64

In [70]:
#6.ən yaşlı və ən gənc sərnişinlərin yaşı neçədir?
young=df["Age"].min()
old=df["Age"].max()
old

np.float64(80.0)

In [77]:
#7.Sərnişinlərdən neçəsi ailə üzvləriylə bir yerdə səyahət edib? sibsp qradas baci sayi parch valideyn sayi
df[(df["SibSp"]+df["Parch"])>0].count()[["Survived"]]
#df[(df["SibSp"]+df["Parch"])>0].shape[0] --setr sayi

Survived    354
dtype: int64

In [82]:
##8.Bütün Kabin nömrələrini göstərin (təkrarlanmasın)
df["Cabin"].dropna().unique()##nan silib

array(['C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33', 'F G73', 'E31',
       'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69', 'D47',
       'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4', 'A32', 'B4',
       'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35', 'C87', 'B77',
       'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19', 'B49', 'D',
       'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66', 'C7',
       'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128', 'D37',
       'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44', 'A34', 'C104',
       'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30',
       'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22',
       'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20',
       'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126',
       'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63', 'C62 C64',
       'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30', 'E121',
       'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36', 'B102',
       'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42', 'C148'],
      dtype=object)